#!/bin/bash

mkdir -p $HOME/.vo/objs
mkdir -p $HOME/.bash_completion.d/
ln -sf `pwd`/vo_completion $HOME/.bash_completion.d/vo_completion
mkdir -p $HOME/.vim
sudo ln -sf `pwd`/bin/vo /usr/bin/vo
ln -sf `pwd`/configure $HOME/.vo/.configure
ln -sf `pwd`/template $HOME/.vo/.template
ln -sf `pwd`/vimrc $HOME/.vimrc
sudo cp -R vim/* $HOME/.vim/
sudo chmod 777 $HOME/.vim/
cd $HOME/.vim/bundle/YouCompleteMe/third_party/ycmd
python3 build.py
